package com.centit.supervise.po;

// Generated 2013-12-20 16:41:04 by Hibernate Tools 3.4.0.CR1

import java.util.Date;

/**
 * Supinfocjjc generated by hbm2java
 */
public class SuperviseCJJC implements java.io.Serializable {
    private static final long serialVersionUID = 1L;
    private String supervisecode;
    private String no;
    private String complaintid;
    private String supervisetype;
    private String superviseoption;
    private String superviseback;
    private String superviseresult;
    private String operatorid;
    private Date superdate;
    private Date receiptdate;
    private Date enddate;
    private Boolean isexternal;
    private Character issuperviseupload;
    private Character isreceiptupload;
    private Character isendupload;
    private String dealstep;
    private String backoperatorname;
    private String endoperatorid;
    private Date promise;
    private String receiveoperatorlist;
    private Character ischeck;
    private String supervisesource;
    private String warnsortno;
    private String orgId;
    private String superviseuploadno;
    private String supervisiontype;
    private String supervisionyear;
    private String supervisionmonth;
    private String oldOutwayType;
    private String operatorname;
    private String endoperatorname;

    public String getOperatorname() {
        return operatorname;
    }

    public void setOperatorname(String operatorname) {
        this.operatorname = operatorname;
    }

    public String getEndoperatorname() {
        return endoperatorname;
    }

    public void setEndoperatorname(String endoperatorname) {
        this.endoperatorname = endoperatorname;
    }

    public String getOldOutwayType() {
        return oldOutwayType;
    }

    public void setOldOutwayType(String oldOutwayType) {
        this.oldOutwayType = oldOutwayType;
    }

    public SuperviseCJJC() {
    }

    public SuperviseCJJC(String supervisecode, Date promise) {
        this.supervisecode = supervisecode;
        this.promise = promise;
    }

    public SuperviseCJJC(String supervisecode, String no, String complaintid,
            String supervisetype, String superviseoption, String superviseback,
            String superviseresult, String operatorid, Date superdate,
            Date receiptdate, Date enddate, Boolean isexternal,
            Character issuperviseupload, Character isreceiptupload,
            Character isendupload, String dealstep, String backoperatorname,
            String endoperatorid, Date promise, String receiveoperatorlist,
            Character ischeck, String supervisesource, String warnsortno,
            String orgId, String superviseuploadno, String supervisiontype,
            String supervisionyear, String supervisionmonth) {
        this.supervisecode = supervisecode;
        this.no = no;
        this.complaintid = complaintid;
        this.supervisetype = supervisetype;
        this.superviseoption = superviseoption;
        this.superviseback = superviseback;
        this.superviseresult = superviseresult;
        this.operatorid = operatorid;
        this.superdate = superdate;
        this.receiptdate = receiptdate;
        this.enddate = enddate;
        this.isexternal = isexternal;
        this.issuperviseupload = issuperviseupload;
        this.isreceiptupload = isreceiptupload;
        this.isendupload = isendupload;
        this.dealstep = dealstep;
        this.backoperatorname = backoperatorname;
        this.endoperatorid = endoperatorid;
        this.promise = promise;
        this.receiveoperatorlist = receiveoperatorlist;
        this.ischeck = ischeck;
        this.supervisesource = supervisesource;
        this.warnsortno = warnsortno;
        this.orgId = orgId;
        this.superviseuploadno = superviseuploadno;
        this.supervisiontype = supervisiontype;
        this.supervisionyear = supervisionyear;
        this.supervisionmonth = supervisionmonth;
    }

    public String getSupervisecode() {
        return this.supervisecode;
    }

    public void setSupervisecode(String supervisecode) {
        this.supervisecode = supervisecode;
    }

    public String getNo() {
        return this.no;
    }

    public void setNo(String no) {
        this.no = no;
    }

    public String getComplaintid() {
        return this.complaintid;
    }

    public void setComplaintid(String complaintid) {
        this.complaintid = complaintid;
    }

    public String getSupervisetype() {
        return this.supervisetype;
    }

    public void setSupervisetype(String supervisetype) {
        this.supervisetype = supervisetype;
    }

    public String getSuperviseoption() {
        return this.superviseoption;
    }

    public void setSuperviseoption(String superviseoption) {
        this.superviseoption = superviseoption;
    }

    public String getSuperviseback() {
        return this.superviseback;
    }

    public void setSuperviseback(String superviseback) {
        this.superviseback = superviseback;
    }

    public String getSuperviseresult() {
        return this.superviseresult;
    }

    public void setSuperviseresult(String superviseresult) {
        this.superviseresult = superviseresult;
    }

    public String getOperatorid() {
        return this.operatorid;
    }

    public void setOperatorid(String operatorid) {
        this.operatorid = operatorid;
    }

    public Date getSuperdate() {
        return this.superdate;
    }

    public void setSuperdate(Date superdate) {
        this.superdate = superdate;
    }

    public Date getReceiptdate() {
        return this.receiptdate;
    }

    public void setReceiptdate(Date receiptdate) {
        this.receiptdate = receiptdate;
    }

    public Date getEnddate() {
        return this.enddate;
    }

    public void setEnddate(Date enddate) {
        this.enddate = enddate;
    }

    public Boolean getIsexternal() {
        return this.isexternal;
    }

    public void setIsexternal(Boolean isexternal) {
        this.isexternal = isexternal;
    }

    public Character getIssuperviseupload() {
        return this.issuperviseupload;
    }

    public void setIssuperviseupload(Character issuperviseupload) {
        this.issuperviseupload = issuperviseupload;
    }

    public Character getIsreceiptupload() {
        return this.isreceiptupload;
    }

    public void setIsreceiptupload(Character isreceiptupload) {
        this.isreceiptupload = isreceiptupload;
    }

    public Character getIsendupload() {
        return this.isendupload;
    }

    public void setIsendupload(Character isendupload) {
        this.isendupload = isendupload;
    }

    public String getDealstep() {
        return this.dealstep;
    }

    public void setDealstep(String dealstep) {
        this.dealstep = dealstep;
    }

    public String getBackoperatorname() {
        return this.backoperatorname;
    }

    public void setBackoperatorname(String backoperatorname) {
        this.backoperatorname = backoperatorname;
    }

    public String getEndoperatorid() {
        return this.endoperatorid;
    }

    public void setEndoperatorid(String endoperatorid) {
        this.endoperatorid = endoperatorid;
    }

    public Date getPromise() {
        return this.promise;
    }

    public void setPromise(Date promise) {
        this.promise = promise;
    }

    public String getReceiveoperatorlist() {
        return this.receiveoperatorlist;
    }

    public void setReceiveoperatorlist(String receiveoperatorlist) {
        this.receiveoperatorlist = receiveoperatorlist;
    }

    public Character getIscheck() {
        return this.ischeck;
    }

    public void setIscheck(Character ischeck) {
        this.ischeck = ischeck;
    }

    public String getSupervisesource() {
        return this.supervisesource;
    }

    public void setSupervisesource(String supervisesource) {
        this.supervisesource = supervisesource;
    }

    public String getWarnsortno() {
        return this.warnsortno;
    }

    public void setWarnsortno(String warnsortno) {
        this.warnsortno = warnsortno;
    }

    public String getOrgId() {
        return this.orgId;
    }

    public void setOrgId(String orgId) {
        this.orgId = orgId;
    }

    public String getSuperviseuploadno() {
        return this.superviseuploadno;
    }

    public void setSuperviseuploadno(String superviseuploadno) {
        this.superviseuploadno = superviseuploadno;
    }

    public String getSupervisiontype() {
        return this.supervisiontype;
    }

    public void setSupervisiontype(String supervisiontype) {
        this.supervisiontype = supervisiontype;
    }

    public String getSupervisionyear() {
        return this.supervisionyear;
    }

    public void setSupervisionyear(String supervisionyear) {
        this.supervisionyear = supervisionyear;
    }

    public String getSupervisionmonth() {
        return this.supervisionmonth;
    }

    public void setSupervisionmonth(String supervisionmonth) {
        this.supervisionmonth = supervisionmonth;
    }

}
