prompt PL/SQL Developer import file
prompt Created on 2014年5月5日 by jf
set feedback off
set define off
prompt Disabling triggers for F_DATACATALOG...
alter table F_DATACATALOG disable all triggers;
prompt Disabling triggers for F_DATADICTIONARY...
alter table F_DATADICTIONARY disable all triggers;
prompt Loading F_DATACATALOG...
insert into F_DATACATALOG (CATALOGCODE, CATALOGNAME, CATALOGSTYLE, CATALOGTYPE, CATALOGDESC, FIELDDESC, ISUPLOAD, DICTIONARYTYPE)
values ('INDUSTRY_TYPE2', '行业类型2', 'U', 'L', null, null, '0', null);
insert into F_DATACATALOG (CATALOGCODE, CATALOGNAME, CATALOGSTYLE, CATALOGTYPE, CATALOGDESC, FIELDDESC, ISUPLOAD, DICTIONARYTYPE)
values ('ITEM_TYPE2', '权力类型', 'U', 'L', '权力类型', '权力类型', '0', null);
commit;
prompt 2 records loaded
prompt Loading F_DATADICTIONARY...
insert into F_DATADICTIONARY (CATALOGCODE, DATACODE, EXTRACODE, EXTRACODE2, DATATAG, DATAVALUE, DATASTYLE, DATADESC)
values ('INDUSTRY_TYPE2', 'GK', 'e', null, 'T', '港口', null, null);
insert into F_DATADICTIONARY (CATALOGCODE, DATACODE, EXTRACODE, EXTRACODE2, DATATAG, DATAVALUE, DATASTYLE, DATADESC)
values ('INDUSTRY_TYPE2', 'GL', 'a', null, 'T', '公路', null, null);
insert into F_DATADICTIONARY (CATALOGCODE, DATACODE, EXTRACODE, EXTRACODE2, DATATAG, DATAVALUE, DATASTYLE, DATADESC)
values ('INDUSTRY_TYPE2', 'HD', 'c', null, 'T', '航道', null, null);
insert into F_DATADICTIONARY (CATALOGCODE, DATACODE, EXTRACODE, EXTRACODE2, DATATAG, DATAVALUE, DATASTYLE, DATADESC)
values ('INDUSTRY_TYPE2', 'HS', 'd', null, 'T', '海事', null, null);
insert into F_DATADICTIONARY (CATALOGCODE, DATACODE, EXTRACODE, EXTRACODE2, DATATAG, DATAVALUE, DATASTYLE, DATADESC)
values ('INDUSTRY_TYPE2', 'JS', 'f', null, 'T', '建设', null, null);
insert into F_DATADICTIONARY (CATALOGCODE, DATACODE, EXTRACODE, EXTRACODE2, DATATAG, DATAVALUE, DATASTYLE, DATADESC)
values ('INDUSTRY_TYPE2', 'QT', 'h', null, null, '其他', null, null);
insert into F_DATADICTIONARY (CATALOGCODE, DATACODE, EXTRACODE, EXTRACODE2, DATATAG, DATAVALUE, DATASTYLE, DATADESC)
values ('INDUSTRY_TYPE2', 'YG', 'b', null, 'T', '运管', null, null);
insert into F_DATADICTIONARY (CATALOGCODE, DATACODE, EXTRACODE, EXTRACODE2, DATATAG, DATAVALUE, DATASTYLE, DATADESC)
values ('INDUSTRY_TYPE2', 'ZJ', 'g', null, 'T', '质监', null, null);
insert into F_DATADICTIONARY (CATALOGCODE, DATACODE, EXTRACODE, EXTRACODE2, DATATAG, DATAVALUE, DATASTYLE, DATADESC)
values ('ITEM_TYPE2', 'CF', null, 'B', 'T', '处罚', 'S', null);
insert into F_DATADICTIONARY (CATALOGCODE, DATACODE, EXTRACODE, EXTRACODE2, DATATAG, DATAVALUE, DATASTYLE, DATADESC)
values ('ITEM_TYPE2', 'CJ', null, 'K', 'T', '裁决', 'S', null);
insert into F_DATADICTIONARY (CATALOGCODE, DATACODE, EXTRACODE, EXTRACODE2, DATATAG, DATAVALUE, DATASTYLE, DATADESC)
values ('ITEM_TYPE2', 'FW', null, 'H', 'T', '服务', 'S', null);
insert into F_DATADICTIONARY (CATALOGCODE, DATACODE, EXTRACODE, EXTRACODE2, DATATAG, DATAVALUE, DATASTYLE, DATADESC)
values ('ITEM_TYPE2', 'GF', null, 'F', 'T', '给付', 'S', null);
insert into F_DATADICTIONARY (CATALOGCODE, DATACODE, EXTRACODE, EXTRACODE2, DATATAG, DATAVALUE, DATASTYLE, DATADESC)
values ('ITEM_TYPE2', 'JL', null, 'G', 'T', '奖励', 'S', null);
insert into F_DATADICTIONARY (CATALOGCODE, DATACODE, EXTRACODE, EXTRACODE2, DATATAG, DATAVALUE, DATASTYLE, DATADESC)
values ('ITEM_TYPE2', 'QR', null, 'I', 'T', '确认  ', 'S', null);
insert into F_DATADICTIONARY (CATALOGCODE, DATACODE, EXTRACODE, EXTRACODE2, DATATAG, DATAVALUE, DATASTYLE, DATADESC)
values ('ITEM_TYPE2', 'QT', null, 'L', 'T', '其他', 'S', null);
insert into F_DATADICTIONARY (CATALOGCODE, DATACODE, EXTRACODE, EXTRACODE2, DATATAG, DATAVALUE, DATASTYLE, DATADESC)
values ('ITEM_TYPE2', 'QZ', null, 'D', 'T', '强制', 'S', null);
insert into F_DATADICTIONARY (CATALOGCODE, DATACODE, EXTRACODE, EXTRACODE2, DATATAG, DATAVALUE, DATASTYLE, DATADESC)
values ('ITEM_TYPE2', 'SP', null, 'E', 'T', '审批', 'S', null);
insert into F_DATADICTIONARY (CATALOGCODE, DATACODE, EXTRACODE, EXTRACODE2, DATATAG, DATAVALUE, DATASTYLE, DATADESC)
values ('ITEM_TYPE2', 'XK', null, 'A', 'T', '许可', 'S', null);
insert into F_DATADICTIONARY (CATALOGCODE, DATACODE, EXTRACODE, EXTRACODE2, DATATAG, DATAVALUE, DATASTYLE, DATADESC)
values ('ITEM_TYPE2', 'ZS', null, 'C', 'T', '征收', 'S', null);
insert into F_DATADICTIONARY (CATALOGCODE, DATACODE, EXTRACODE, EXTRACODE2, DATATAG, DATAVALUE, DATASTYLE, DATADESC)
values ('ITEM_TYPE2', 'ZY', null, 'J', 'T', '征用', 'S', null);
commit;
prompt 20 records loaded
prompt Enabling triggers for F_DATACATALOG...
alter table F_DATACATALOG enable all triggers;
prompt Enabling triggers for F_DATADICTIONARY...
alter table F_DATADICTIONARY enable all triggers;
set feedback on
set define on
prompt Done.
